# Generated by Django 2.2.3 on 2019-07-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prepaidplans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=100)),
                ('planprice', models.FloatField()),
                ('planduration', models.IntegerField()),
                ('plandes', models.TextField()),
            ],
        ),
    ]
