# Generated by Django 2.2.4 on 2019-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dongleform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('postedby', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Dongleform',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dongleplans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=10)),
                ('validity', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Dongleplan',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('femail', models.CharField(max_length=100)),
                ('fsubject', models.CharField(max_length=100)),
                ('fmessage', models.CharField(max_length=1000)),
                ('postedby', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('postedby', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mnpform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('newmob', models.CharField(max_length=10)),
                ('postedby', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Mnpform',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Postform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('num', models.CharField(max_length=10)),
                ('postedby', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Postform',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Preform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('num', models.CharField(max_length=10)),
                ('postedby', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Preform',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Prepaidplans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=100)),
                ('planprice', models.FloatField()),
                ('planduration', models.IntegerField()),
                ('plandes', models.TextField()),
            ],
            options={
                'ordering': ('planprice',),
            },
        ),
        migrations.CreateModel(
            name='Pretopostform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('newmob', models.CharField(max_length=10)),
                ('postedby', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Pretopostform',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('rdate', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=10)),
                ('postedby', models.CharField(max_length=10)),
            ],
        ),
    ]
