# Generated by Django 2.2.3 on 2019-07-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepaidplans',
            options={'ordering': ('planprice',)},
        ),
    ]
