# Generated by Django 2.2.4 on 2019-08-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
