# Generated by Django 2.2.4 on 2019-08-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_feedback_mnpform_pretopostform'),
    ]

    operations = [
        migrations.AddField(
            model_name='preform',
            name='num',
            field=models.CharField(default=8056969732, max_length=10),
            preserve_default=False,
        ),
    ]
