# Generated by Django 2.2.4 on 2019-08-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20190815_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongleform',
            name='postedby',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='postedby',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='postedby',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='preform',
            name='postedby',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pretopostform',
            name='postedby',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='postedby',
            field=models.CharField(max_length=15),
        ),
    ]
