# Generated by Django 2.2.4 on 2019-08-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='password',
            new_name='phone',
        ),
    ]
