# Generated by Django 2.2.4 on 2019-08-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20190815_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnpform',
            name='postedby',
            field=models.CharField(max_length=10),
        ),
    ]
