# Generated by Django 2.2.4 on 2019-08-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20190811_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dongleplans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=10)),
                ('validity', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Dongleplan',
                'ordering': ('price',),
            },
        ),
    ]
