# Generated by Django 2.2.3 on 2019-08-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_dongleplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='rdate',
            field=models.CharField(default=0.05263157894736842, max_length=50),
            preserve_default=False,
        ),
    ]
