# Generated by Django 2.2.4 on 2019-08-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fsubject',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='femail',
            field=models.CharField(max_length=100),
        ),
    ]
