# Generated by Django 2.2.4 on 2019-08-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_recharge_rdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='username',
        ),
    ]
