# Generated by Django 2.2.4 on 2019-08-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20190812_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='pid',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
